### ISSUE TITLE
微信6.7.3 play版无法正常使用

### ISSUE THREAD

**Issue by sukanka** [valord577/auto_add_wechat_friends_py#1]
您好,我在我的一加3上无法正常使用(可以模拟点击),修改代码后部分功能可以正常使用
devices info:
 ONEPLUS A3000 
Android 8.0.0
WeChat: 6.7.3 Google Play

主要是界面显示的文字不一样造成的bug,下图是修改前后`main.py` 文件的对比,
第70行的`搜索：`那里您使用了中文的冒号，微信实际的是英文冒号
![image](https://user-images.githubusercontent.com/31362108/48298909-32369a00-e500-11e8-9c0b-83fa03e41ce4.png)
![image](https://user-images.githubusercontent.com/31362108/48298917-5f834800-e500-11e8-97af-4dfe1547520c.png)
![image](https://user-images.githubusercontent.com/31362108/48298934-a8d39780-e500-11e8-9cd8-5989043fad40.png)
同时`main.py` 中的第196行在python3.7上报错(修改了普通文字后）
![image](https://user-images.githubusercontent.com/31362108/48298987-3d3dfa00-e501-11e8-9ae7-eb4e569f9a74.png)

报错信息如下：
```
Traceback (most recent call last):
  File "run.py", line 90, in <module>
    run(sys.argv[1:])
  File "run.py", line 43, in run
    fun.main()
  File "****\auto_add_wechat_friends_py-master\main.py", line 196, in main
    with self._file.open(self._file) as f:
AttributeError: 'str' object has no attribute 'open'
```
我使用时将该行改成了直接打开文件，就可以使用(绝对路径）
代码如下： `with open(r'D:\dadada\data\name.txt',encoding='UTF-8') as f:`

**Comment by sukanka** [comment]
此外，手机输入法必须事先调成英文，并且要qwerty 键盘上有数字键才能正常使用

**Comment by valord577** [comment]
谢谢反馈。 这么多问题是因为我个人没有写具体的使用方法。
1. 关于`man.py`需要修改文字这一块 我测试对象是企业微信 而不是微信(非play版) 当中的点击逻辑需要适当的修改 才能使用；
2. `main.py` 中的第196行在python3.7上报错这个问题 我看你的操作系统是win/dos 我暂时没有测试到 接下来有时间测试之后 我会详细反馈；
3. 手机输入法必须事先调成英文，并且要qwerty 键盘上有数字键才能正常使用这个问题 因为我的测试机用的是asop键盘 没有使用第三方输入法 发布的时候也没有发现。同第二点 详细测试后会反馈。

**Comment by duhaitao2016** [comment]
> 谢谢反馈。 这么多问题是因为我个人没有写具体的使用方法。
> 
> 1. 关于`man.py`需要修改文字这一块 我测试对象是企业微信 而不是微信(非play版) 当中的点击逻辑需要适当的修改 才能使用；
> 2. `main.py` 中的第196行在python3.7上报错这个问题 我看你的操作系统是win/dos 我暂时没有测试到 接下来有时间测试之后 我会详细反馈；
> 3. 手机输入法必须事先调成英文，并且要qwerty 键盘上有数字键才能正常使用这个问题 因为我的测试机用的是asop键盘 没有使用第三方输入法 发布的时候也没有发现。同第二点 详细测试后会反馈。

输入法其实不用调，只是要在输入之前加一次刷新，就可以了
