### ISSUE TITLE
bug 一堆，能在md文档写个使用流程吗

### ISSUE THREAD

**Issue by JszCloud** [valord577/auto_add_wechat_friends_py#2]
▶ python3 run.py -d
UI hierchary dumped to: /sdcard/dump.xml
/sdcard/dump.xml: 1 file pulled. 5.2 MB/s (23633 bytes in 0.004s)
Traceback (most recent call last):
  File "run.py", line 90, in <module>
    run(sys.argv[1:])
  File "run.py", line 43, in run
    fun.main()
  File "/Users/lmy/dev/android/wechat/auto_add_wechat_friends_py/main.py", line 193, in main
    self.init()
  File "/Users/lmy/dev/android/wechat/auto_add_wechat_friends_py/main.py", line 58, in init
    self._adb.click_by_text_after_refresh('通讯录')
  File "/Users/lmy/dev/android/wechat/auto_add_wechat_friends_py/adb.py", line 132, in click_by_text_after_refresh
    self.click_by_text(text, index)
  File "/Users/lmy/dev/android/wechat/auto_add_wechat_friends_py/adb.py", line 124, in click_by_text
    self.click(0)
  File "/Users/lmy/dev/android/wechat/auto_add_wechat_friends_py/adb.py", line 119, in click
    self.cal_coordinate(cal_index)
  File "/Users/lmy/dev/android/wechat/auto_add_wechat_friends_py/adb.py", line 104, in cal_coordinate
    _bounds = self._nodes[_index]['bounds']
IndexError: list index out of range

**Comment by valord577** [comment]
好的 谢谢反馈 我之后会把具体的使用方法写个md补上。
根据你的exception来看 是没有选定第一个页面。

click_by_text_after_refresh('通讯录') 
这个方法是需要在微信/企业微信底部菜单栏有通讯录三个字的时候才会点击成功。
你看下运行这个项目的时候 手机屏幕是不是打开微信的
