### ISSUE TITLE
咋回事啊？大佬

### ISSUE THREAD

**Issue by yxwLearn** [valord577/auto_add_wechat_friends_py#5]
Active code page: 65001
ERROR: null root node returned by UiTestAutomationBridge.
Active code page: 65001
/sdcard/dump.xml: 1 file pulled. 7.1 MB/s (29588 bytes in 0.004s)
Traceback (most recent call last):
  File "run.py", line 90, in <module>
    run(sys.argv[1:])
  File "run.py", line 43, in run
    fun.main()
  File "G:\auto_add_wechat_friends_py-master\main.py", line 193, in main
    self.init()
  File "G:\auto_add_wechat_friends_py-master\main.py", line 58, in init
    self._adb.click_by_text_after_refresh('通讯录')
  File "G:\auto_add_wechat_friends_py-master\adb.py", line 132, in click_by_text_after_refresh
    self.click_by_text(text, index)
  File "G:\auto_add_wechat_friends_py-master\adb.py", line 124, in click_by_text
    self.click(0)
  File "G:\auto_add_wechat_friends_py-master\adb.py", line 119, in click
    self.cal_coordinate(cal_index)
  File "G:\auto_add_wechat_friends_py-master\adb.py", line 104, in cal_coordinate
    _bounds = self._nodes[_index]['bounds']
IndexError: list index out of range

**Comment by yxwLearn** [comment]
@valord577 
只适用于企业微信吗？

**Comment by yxwLearn** [comment]
@valord577 

G:\auto_add_wechat_friends_py-master>adb shell uiautomator dump /sdcard/dump.xml
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
ERROR: null root node returned by UiTestAutomationBridge.

**Comment by dejianstankovic** [comment]
你这个是不是用了 多开助手 复制出来的 程序才会出现 null root node returned by UiTestAutomationBridge.
